
values: 
  request:
    parameters:
      organization: ( devops.organization )
      project: ( devops.project )

operations:

- message: Listing build queues
  request: apis/devops/distributedtask-queue-list.yaml
  output:
    devops:
      queues: (result.body.value)

- message: Listing policy types
  request: apis/devops/Policy/Types/List.yaml
  output:
    devops:
      policy:
        types: (result.body.value)

- message: Listing policy configurations
  request: apis/devops/Policy/Configurations/List.yaml
  output:
    devops:
      policies: (result.body.value)

- message: Listing groups
  request: apis/devops/Graph/Groups/List.yaml
  output:
    devops:
      graph:
        groups: (result.body.value)

{{# each devops.repository }}
- message: Processing repository {{ name }}
  values:
    repository: ( devops.repository.{{ @key }} )
    request:
      parameters:
        repositoryId: {{ name }}

  operations:
  - message: Finding existing git repository
    request: apis/devops/Git/Repositories/GetRepository.yaml
    output:
      properties: (result.body)

  output:
    devops:
      repository:
        {{ @key }}:
          id: (properties.id)
          properties: (properties)
{{/ each }}

{{# each devops.build }}
- message: "Processing build {{ path }}\\\\{{ name }}"
  values:
    repository: (devops.repository.{{ repository }}.properties)
    queue: ( devops.queues[?name=='{{ queue }}'] | [0] )
    build: (devops.build.{{ @key }})

  operations:
  - message: Finding existing build definition
    values:
      request:
        parameters:
          name: "{{ name }}"
          path: "{{ path }}"
    request: apis/devops/Build/Definitions/List.yaml
    output:
      build:
        id: "( result.body.value[?name=='{{ name }}' && path=='{{ path }}'] | [0].id )"
        revision: "( result.body.value[?name=='{{ name }}' && path=='{{ path }}'] | [0].revision )"
        
  - message: Getting build definition details
    values:
      request:
        parameters:
          definitionId: ( build.id )
    condition: (build.id != null)
    request: apis/devops/Build/Definitions/Get.yaml
    output:
      existing: (result.body)

  - message: Create or update build definition
    request: apis/devops/build-definition-save.yaml
    output:
      properties: (result.body)

  output:
    devops:
      build:
        {{ @key }}:
          properties: (properties)
{{/ each }}

{{# each devops.release }}
- message: "Processing release {{ path }}\\\\{{ name }}"
  values:
    build: ( devops.build.{{ build }}.properties )
    queue: ( devops.queues[?name=='{{ queue }}'] | [0] )
    release: (devops.release.{{ @key }})  

  operations:
  - message: Finding existing release definition
    values:
      request:
        parameters:
          searchText: "{{ name }}"
          path: "{{ path }}"
          isExactNameMatch: true
    request: apis/devops/Release/Definitions/List.yaml
    output: "( result.body.value[?name=='{{ name }}' && path=='{{ path }}'] | [0].{release:{id:id, revision:revision}} )"

  - message: Getting release definition details
    condition: (release.id != null)
    values:
      request:
        parameters:
          definitionId: ( release. id )
    request: apis/devops/Release/Definitions/Get.yaml
    output:
      existing: (result.body)

  - message: Create or update release definition
    request: apis/devops/release-definition-save.yaml
    output:
      properties: (result.body)

  output:
    devops:
      release:
        {{ @key }}:
          properties: (properties)
{{/ each }}

{{# each devops.repository }}
- message: Processing policy for repository {{ name }}
  values:
    repository: ( devops.repository.{{ @key }} )

  operations:
  - template: branch-policy-assign-properties.yaml
    output: (result)

  - message: Building branch policy list
    template: branch-policy-build-list.yaml
    output: 
      foreach: (result)

  - message: Saving branch policies
    condition: (length(foreach || `[]`) != `0` )
    operations:
    - message: (['Updating "', foreach[0].type.displayName, '" on branch ', foreach[0].settings.scope[0].refName])
      condition: ( foreach[0].id != null )
      values:
        request:
          parameters:
            configurationId: ( foreach[0].id )
          body: ( foreach[0] )
      request: apis/devops/Policy/Configurations/Update.yaml
      output:
        policy: ( result.body.to_object( [[ to_string(id), {properties:@} ]] ) )
    - message: (['Creating "', foreach[0].type.displayName, '" on branch ', foreach[0].settings.scope[0].refName])
      condition: ( foreach[0].id == null )
      values:
        request:
          body: ( foreach[0] )
      request: apis/devops/Policy/Configurations/Create.yaml
      output:
        policy: ( result.body.to_object( [[ to_string(id), {properties:@} ]] ) )
    output:
      foreach: ( foreach[1:] )
      policy: ( policy )
    repeat:
      condition: ( length(foreach) != `0` )
  output:
    policy: ( policy )
{{/ each }}

output:
  repository: ( to_object( items(devops.repository)[*].[[0], [1].properties] ) )
  build: ( to_object( items(devops.build)[*].[[0], [1].properties] ) )
  release: ( to_object( items(devops.release)[*].[[0], [1].properties] ) )
  policy: ( to_object( items(policy)[*].[[0], [1].properties] ) )
