{{# if policy.id }}
# https://docs.microsoft.com/en-us/rest/api/vsts/policy/configurations/update?view=vsts-rest-5.0
method: PUT
url: https://dev.azure.com/{{ devops.organization }}/{{ devops.project }}/_apis/policy/configurations/{{ policy.id }}?api-version=5.0-preview.1
{{ else }}
# https://docs.microsoft.com/en-us/rest/api/vsts/policy/configurations/create?view=vsts-rest-5.0
method: POST
url: https://dev.azure.com/{{ devops.organization }}/{{ devops.project }}/_apis/policy/configurations?api-version=5.0-preview.1
{{/ if }}
auth:
  resource: 499b84ac-1321-427f-aa17-267ca6975798
  client: e8f3cc86-b3b2-4ebb-867c-9c314925b384
body: {{{ json policy }}}
  