{{# if release.id }}
# https://docs.microsoft.com/en-us/rest/api/vsts/release/definitions/update?view=vsts-rest-5.0
method: PUT
url: https://vsrm.dev.azure.com/{{ devops.organization }}/{{ devops.project }}/_apis/release/definitions/{{ release.id }}?api-version=5.0-preview.3
{{ else }}
# https://docs.microsoft.com/en-us/rest/api/vsts/release/definitions/create?view=vsts-rest-5.0
method: POST
url: https://vsrm.dev.azure.com/{{ devops.organization }}/{{ devops.project }}/_apis/release/definitions?api-version=5.0-preview.3
{{/ if }}
auth:
  resource: 499b84ac-1321-427f-aa17-267ca6975798
  client: e8f3cc86-b3b2-4ebb-867c-9c314925b384
body:
{{# if release.id }}
  id: {{ release.id }}
  revision: {{ release.revision }}
{{/ if }}
  name: "{{ release.name }}"
  path: "{{ release.path }}"
  description: "{{ release.description }}"
  comment: Saved by Atlas workflow 403-devops-pipelines
  artifacts:
  - type: build
    alias: _{{ build.name }}
    sourceId: {{ build.project.id }}
    isPrimary: true
    isRetained: true
    definitionReference:
      project:
        id: {{ build.project.id }}
        name: {{ build.project.name }}
      definition:
        id: {{ build.id }}
        name: {{ build.name }}
      defaultVersionType:
        id: latestType
        name: Latest
  triggers:
  - triggerType: artifactSource
    artifactAlias: _{{ build.name }}
    triggerConditions: {{{ json release.triggerConditions }}}    
  environments:
{{# each release.stages }}
  - name: {{ name }}
    {{# query "(existing.environments[?name==`$1`])" name existing=../existing }}
    id: {{ id }}
    owner:
      id: {{ owner.id }}
    {{/query}}
    rank: {{{ query "sum([`$1`, `1`])" @index }}}
    retentionPolicy:
      daysToKeep: 30
      releasesToKeep: 3
      retainBuild: true
    conditions:
    - conditionType: event
      name: ReleaseStarted
    preDeployApprovals:
      approvals:
      - rank: 1
        {{# query "(existing.environments[?name==`$1`].preDeployApprovals.approvals[?rank==`1`][])" name existing=../existing }}
        id: {{ id }}
        {{/ query }}
        isAutomated: true
        isNotificationOn: false
    postDeployApprovals:
      approvals:
      - rank: 1
        {{# query "(existing.environments[?name==`$1`].postDeployApprovals.approvals[?rank==`1`][])" name existing=../existing }}
        id: {{ id }}
        {{/ query }}
        isAutomated: true
        isNotificationOn: false
    {{# query "(existing.environments[?name==`$1`].deployStep)" name existing=../existing }}
    deployStep:
      id: {{ id }}
    {{/ query }}
    deployPhases:
    - rank: 1
      phaseType: agentBasedDeployment
      name: Agent job
      deploymentInput:
        queueId: {{ ../queue.id }}
      workflowTasks: {{{ json steps }}}

{{/ each }}
