

operations:
- message: Listing Microsoft Azure tenants, see https://docs.microsoft.com/en-us/rest/api/resources/subscriptions/list
  request: apis/azure/SubscriptionClient/Tenants/List.yaml
  output:
    tenants: ( result.body.value[] )

- message: ( ['Processing tenant ', tenant.tenantId] )
  foreach:
    values:
      tenant: ( tenants[] )
      azure:
        tenant: ( tenants[].tenantId )
      request:
        parameters:
          tenantID: ( tenants[].tenantId )
    output:
      tenants: ( [tenant] )

  operations:
  - message: Getting Microsoft Graph user info, see https://docs.microsoft.com/en-us/rest/api/graphrbac/objects/getcurrentuser
    request: apis/graph/GraphRbacManagementClient/SignedInUser/Get.yaml
    output:
      tenant:
        user: ( result.body.{ "odata.type":"odata.type", objectId:objectId, displayName:displayName, userPrincipalName:userPrincipalName, otherMails:otherMails } )

  - message: Listing Active Directory domains, see https://docs.microsoft.com/en-us/rest/api/graphrbac/domains/list
    request: apis/graph/GraphRbacManagementClient/Domain/Domains_List.yaml
    output:
      tenant:
        domains: ( result.body.value[].name )

  - message: Listing Microsoft Azure subscriptions, see https://docs.microsoft.com/en-us/rest/api/resources/subscriptions/list
    request: apis/azure/SubscriptionClient/Subscriptions/List.yaml
    output:
      tenant:
        subscriptions: ( result.body.value[].{ subscriptionId:subscriptionId, displayName:displayName } )


- message: Arranging selection of azure.tenant and azure.subscription
  template: selection.yaml
  write: selection.yaml
  output:
    selection: ( result )
  