
operations:
- message: this workflow is using yaml instead of json
- message: yaml is a super-set of json
- message: yaml file can be written as json, see 01-messages
- message: but it can also use this nice syntax
- message: see http://yaml.org
