
azure:
  # Your Azure Active Directory ID from https://ms.portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/Properties
  # tenant: TENANT_ID             
  # Your Azure Subscription ID from https://ms.portal.azure.com/#blade/Microsoft_Azure_Billing/SubscriptionsBlade
  # subscription: SUBSCRIPTION_ID 
  resourceGroupName: atlas-examples-402
  location: eastus2

storage:
  sku: Standard_LRS
  container: 
    downloads: downloads
    packages: atlas-ci
